### PR TITLE
Added Prime Generator

### PR DESCRIPTION
**Pull request by vamsireddy22**

### CODE REVIEW

**Review by girishtulabandu — CHANGES_REQUESTED** [review]
Kindly read [contribution guidelines](https://github.com/girishtulabandu/One_line_PythonPrograms#contribution-guidelines) before raising the pr

*Your script file should contain only two lines.
    1.comment (what your program does)
    2.Your actual program in single line

**Comment by vamsireddy22** [comment]
Do I need to include script file isn't it?

**Comment by girishtulabandu** [comment]
> Do I need to include script file isn't it?

Yes, create a separate script file for your program. Kindly check the repository to avoid duplications

**Comment by vamsireddy22** [comment]
Can you please check it now. @girishtulabandu

**Comment by girishtulabandu** [comment]
> Can you please check it now. @girishtulabandu

I don't see any changes. Please consider removing print statements. Also, your program should be in single line not in function.

**Comment by girishtulabandu** [comment]
No response

**Pull request closed without merging**
